const langs  = [
    {'lang': 'auto', 'country': 'Automatic'},
    {'lang': 'af', 'country':  'Afrikaans'},
    {'lang': 'sq', 'country':  'Albanian'},
    {'lang': 'am', 'country':  'Amharic'},
    {'lang': 'ar', 'country':  'Arabic'},
    {'lang': 'hy', 'country':  'Armenian'},
    {'lang': 'az', 'country':  'Azerbaijani'},
    {'lang': 'eu', 'country':  'Basque'},
    {'lang': 'be', 'country':  'Belarusian'},
    {'lang': 'bn', 'country':  'Bengali'},
    {'lang': 'bs', 'country':  'Bosnian'},
    {'lang': 'bg', 'country':  'Bulgarian'},
    {'lang': 'ca', 'country':  'Catalan'},
    {'lang': 'ceb', 'country':  'Cebuano'},
    {'lang': 'ny', 'country':  'Chichewa'},
    {'lang': 'zh-cn', 'country':  'Chinese Simplified'},
    {'lang': 'zh-tw', 'country':  'Chinese Traditional'},
    {'lang': 'co', 'country':  'Corsican'},
    {'lang': 'hr', 'country':  'Croatian'},
    {'lang': 'cs', 'country':  'Czech'},
    {'lang': 'da', 'country':  'Danish'},
    {'lang': 'nl', 'country':  'Dutch'},
    {'lang': 'en', 'country':  'English'},
    {'lang': 'eo', 'country':  'Esperanto'},
    {'lang': 'et', 'country':  'Estonian'},
    {'lang': 'tl', 'country':  'Filipino'},
    {'lang': 'fi', 'country':  'Finnish'},
    {'lang': 'fr', 'country':  'French'},
    {'lang': 'fy', 'country':  'Frisian'},
    {'lang': 'gl', 'country':  'Galician'},
    {'lang': 'ka', 'country':  'Georgian'},
    {'lang': 'de', 'country':  'German'},
    {'lang': 'el', 'country':  'Greek'},
    {'lang': 'gu', 'country':  'Gujarati'},
    {'lang': 'ht', 'country':  'Haitian Creole'},
    {'lang': 'ha', 'country':  'Hausa'},
    {'lang': 'haw', 'country':  'Hawaiian'},
    {'lang': 'iw', 'country':  'Hebrew'},
    {'lang': 'hi', 'country':  'Hindi'},
    {'lang': 'hmn', 'country':  'Hmong'},
    {'lang': 'hu', 'country':  'Hungarian'},
    {'lang': 'is', 'country':  'Icelandic'},
    {'lang': 'ig', 'country':  'Igbo'},
    {'lang': 'id', 'country':  'Indonesian'},
    {'lang': 'ga', 'country':  'Irish'},
    {'lang': 'it', 'country':  'Italian'},
    {'lang': 'ja', 'country':  'Japanese'},
    {'lang': 'jw', 'country':  'Javanese'},
    {'lang': 'kn', 'country':  'Kannada'},
    {'lang': 'kk', 'country':  'Kazakh'},
    {'lang': 'km', 'country':  'Khmer'},
    {'lang': 'ko', 'country':  'Korean'},
    {'lang': 'ku', 'country':  'Kurdish (Kurmanji)'},
    {'lang': 'ky', 'country':  'Kyrgyz'},
    {'lang': 'lo', 'country':  'Lao'},
    {'lang': 'la', 'country':  'Latin'},
    {'lang': 'lv', 'country':  'Latvian'},
    {'lang': 'lt', 'country':  'Lithuanian'},
    {'lang': 'lb', 'country':  'Luxembourgish'},
    {'lang': 'mk', 'country':  'Macedonian'},
    {'lang': 'mg', 'country':  'Malagasy'},
    {'lang': 'ms', 'country':  'Malay'},
    {'lang': 'ml', 'country':  'Malayalam'},
    {'lang': 'mt', 'country':  'Maltese'},
    {'lang': 'mi', 'country':  'Maori'},
    {'lang': 'mr', 'country':  'Marathi'},
    {'lang': 'mn', 'country':  'Mongolian'},
    {'lang': 'my', 'country':  'Myanmar (Burmese)'},
    {'lang': 'ne', 'country':  'Nepali'},
    {'lang': 'no', 'country':  'Norwegian'},
    {'lang': 'ps', 'country':  'Pashto'},
    {'lang': 'fa', 'country':  'Persian'},
    {'lang': 'pl', 'country':  'Polish'},
    {'lang': 'pt', 'country':  'Portuguese'},
    {'lang': 'ma', 'country':  'Punjabi'},
    {'lang': 'ro', 'country':  'Romanian'},
    {'lang': 'ru', 'country':  'Russian'},
    {'lang': 'sm', 'country':  'Samoan'},
    {'lang': 'gd', 'country':  'Scots Gaelic'},
    {'lang': 'sr', 'country':  'Serbian'},
    {'lang': 'st', 'country':  'Sesotho'},
    {'lang': 'sn', 'country':  'Shona'},
    {'lang': 'sd', 'country':  'Sindhi'},
    {'lang': 'si', 'country':  'Sinhala'},
    {'lang': 'sk', 'country':  'Slovak'},
    {'lang': 'sl', 'country':  'Slovenian'},
    {'lang': 'so', 'country':  'Somali'},
    {'lang': 'es', 'country':  'Spanish'},
    {'lang': 'su', 'country':  'Sundanese'},
    {'lang': 'sw', 'country':  'Swahili'},
    {'lang': 'sv', 'country':  'Swedish'},
    {'lang': 'tg', 'country':  'Tajik'},
    {'lang': 'ta', 'country':  'Tamil'},
    {'lang': 'te', 'country':  'Telugu'},
    {'lang': 'th', 'country':  'Thai'},
    {'lang': 'tr', 'country':  'Turkish'},
    {'lang': 'uk', 'country':  'Ukrainian'},
    {'lang': 'ur', 'country':  'Urdu'},
    {'lang': 'uz', 'country':  'Uzbek'},
    {'lang': 'vi', 'country':  'Vietnamese'},
    {'lang': 'cy', 'country':  'Welsh'},
    {'lang': 'xh', 'country':  'Xhosa'},
    {'lang': 'yi', 'country':  'Yiddish'},
    {'lang': 'yo', 'country':  'Yoruba'},
    {'lang': 'zu', 'country':  'Zulu'}
]

module.exports = {
    country: langs
}